### ISSUE TITLE
轻国填写好ID,白名单填好了合集的ID，可是登录的时候就被退出了

### ISSUE THREAD

**Issue by Lin1nan279** [ilusrdbb/lightnovel-pydownloader#3]
Version 2.1.2
2024-10-05 18:54:13,962 - lk开始登录...
Press Enter to exit...

就像这样直接退出了，这个是因为什么？，
合集的ID是指图里这个界面的https://www.lightnovel.us/cn/series/5349，5439对吗
![337b285018812d008674e38ba2207b8f](https://github.com/user-attachments/assets/adb8af4c-041f-4a0b-b846-d1a00e1dbb0f)
``

**Comment by ilusrdbb** [comment]
请确认账号密码是否正确以及自身的网络是否能正常访问轻国，部分地区访问轻国可能需要挂代理

轻国白名单例
white_list: [5349]

我建议使用前仔细查看readme的内容
