### ISSUE TITLE
收藏列表爬取失败

### ISSUE THREAD

**Issue by ZuoHuaiBuLuan** [ilusrdbb/lightnovel-pydownloader#4]
我只想下载部分感兴趣的书籍，但是没有单独爬取某本小说的功能，所以我想利用爬取收藏的功能来下载感兴趣的小说。将是否只爬取收藏页由false改为true后就爬取失败，false时是能够正常爬取日轻列表的，是不能识别收藏页的书籍吗

是否只爬取收藏页
get_collection: true
开始页
start_page: 1
结束页 不建议一次抓取过多
end_page: 1

Version 2.1.2
2024-10-10 07:11:13,376 - esj开始登录...
2024-10-10 07:11:15,300 - esj登录成功
2024-10-10 07:11:15,301 - 开始爬取esj第1页
Press Enter to exit...

**Comment by ilusrdbb** [comment]
请确认浏览器在登录状态下访问https://www.esjzone.cc/my/favorite/1是否有收藏书籍
我这边本地测试esj爬收藏没问题
关于单独爬取某本小说，设置白名单即可，例white_list: ['https://www.esjzone.cc/detail/1710846115.html', 'https://www.esjzone.cc/detail/1727757653.html']

**Comment by ZuoHuaiBuLuan** [comment]
不好意思一直没回复，没想到作者这么快当天就回复了
我不管是.me还是.cc域名都是可以看到收藏书籍的，我这几天也试过很多次，不管是把设置里的域名.cc换成.me还是改一些其他设置都还是爬取失败。
我目前的猜测是和登录有关，因为不管在账号填昵称还是邮箱甚至随便填都会显示登录成功，所以我不确定是不是因为没有正常登录所以读取不了收藏页
白名单之前用的这本书https://www.esjzone.cc/detail/1717577824.html不知道为啥一直读取不了显示None 书籍信息已获取，导致我一直以为白名单也用不了，但是今天换了几本书之后才发现可以正常用
不管怎么样还是非常感谢作者提供的软件，实在不行白名单也够用了

**Comment by ZuoHuaiBuLuan** [comment]
> 请确认浏览器在登录状态下访问 https://www.esjzone.cc/my/favorite/1 是否有收藏书籍 我这边本地测试esj爬收藏没问题 关于单独爬取某本小说，设置白名单即可，例white_list: ['https://www.esjzone.cc/detail/1710846115.html', 'https://www.esjzone.cc/detail/1727757653.html']

不好意思一直没回复，没想到作者这么快当天就给答复了
我不管是.me还是.cc域名都是可以看到收藏书籍的，我这几天也试过很多次，不管是把设置里的域名.cc换成.me还是改一些其他设置都还是爬取失败。
我目前的猜测是和登录有关，因为不管在账号填昵称还是邮箱甚至随便填都会显示登录成功，所以我不确定是不是因为没有正常登录所以读取不了收藏页
白名单之前用的这本书[https://www.esjzone.cc/detail/1717577824.html不知道为啥一直读取不了显示None 书籍信息已获取，导致我一直以为白名单也用不了，但是今天换了几本书之后才发现可以正常用
不管怎么样还是非常感谢作者提供的软件，实在不行白名单也够用了

**Comment by ilusrdbb** [comment]
试了下esj登陆时输入密码错误的情况下响应码还是200，看你的描述我也觉得是登录的问题，今天下班后我改下登录失败的提示再发一版

**Comment by ilusrdbb** [comment]
最新版本已添加登录失败时的提示，如果提示“请输入密码”那就是账号或者密码不正确

**Comment by ZuoHuaiBuLuan** [comment]
> 最新版本已添加登录失败时的提示，如果esj响应提示“请输入密码”那就是账号或者密码不正确

感谢，已经顺利下载收藏了👍
