### ISSUE TITLE
希望加入下载txt的功能

### ISSUE THREAD

**Issue by 2023899320** [ilusrdbb/lightnovel-pydownloader#5]
mp3支持不了epub，转换有点麻烦。😭
谢谢作者大大的软件，下小说方便了很多❤️❤️❤️

**Comment by ilusrdbb** [comment]
建议暂时先使用在线工具例如[https://convertio.co/zh/epub-txt/](https://convertio.co/zh/epub-txt/)把导出的epub转成txt
此功能有空的时候会开发，先记下，顺便问下你希望每个章节分别导出一个txt还是合并所有章节为一个txt

**Comment by 2023899320** [comment]
> 建议暂时先使用在线工具例如https://convertio.co/zh/epub-txt/把导出的epub转成txt 此功能有空的时候会开发，先记下，顺便问下你希望每个章节分别导出一个txt还是合并所有章节为一个txt

所有章节，因为一般都是下一整本❤️谢谢作者大大

**Comment by ilusrdbb** [comment]
最新版本已添加导出txt支持，配置项convert_txt设置为true即可，默认导出至txt目录下
功能写的比较糙且未经大量测试，各个网站的格式千奇百怪，先凑合用
