### ISSUE TITLE
lk login error

### ISSUE THREAD

**Issue by Nihility-Protoss** [ilusrdbb/lightnovel-pydownloader#6]
lk的登陆API似乎有改变，简单抓了两个，似乎是修改成类似如下地址了
user:'https://www.lightnovel.us/proxy/api/user/info'
login:'https://www.lightnovel.us/proxy/api/user/login'
可能需要修改一下config.yaml里面的默认配置

**Comment by ilusrdbb** [comment]
提供的api看样子是网页端的，我抓的是app的api，app的api我本地测试是正常的暂时应该不用修改
部分地区登录失败可以尝试挂代理
